version: '3.8'
services:
  embedding:
    build:
      context: ./embedding
      dockerfile: Dockerfile
    # todo does docker networking break rate limiting
    ports:
      - 80:5000
    volumes:
      - ./embedding/dec10_openai:/app/dec10_openai
    restart: unless-stopped
    env_file: .env
